---
kind: "operation"
client: "rug-cli 0.23.0"
editor:
  name: "atomist-rugs.rug-editors.AddRugEditor"
  group: "atomist-rugs"
  artifact: "rug-editors"
  version: "0.8.0"
  origin:
    repo: "https://github.com/atomist-rugs/rug-editors.git"
    branch: "b29e16a2eb08430790d6ef7d72ab2c199786d7c0"
    sha: "b29e16a"
  parameters:
    - "editor_name": "MakeRugLanguageExtension"

---
kind: "operation"
client: "rug-cli 0.23.0"
editor:
  name: "jessitron.scattered-rugs.AddScalaPom"
  group: "jessitron"
  artifact: "scattered-rugs"
  version: "0.2.0"
  origin:
    repo: "git@github.com:jessitron/scattered-rugs.git"
    branch: "master"
    sha: "08b0c19*"
  parameters:
    - "group_id": "something"
    - "artifact_id": "scala-editors"

